version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: monouser
      POSTGRES_PASSWORD: monopass
      POSTGRES_DB: monolith
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monouser -d monolith"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rust_iss:
    build:
      context: ./services/rust_iss
    container_name: rust_iss
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://monouser:monopass@db:5432/monolith
      REDIS_URL: redis://redis:6379

      FALLBACK_ISS_URL: https://api.wheretheiss.at/v1/satellites/25544
      NASA_URL: https://visualization.osdr.nasa.gov/biodata/api/v2/datasets/?format=json
      NASA_KEY: 3Lp1g8dksAXpuVlN4DeaILIkYbZI26rcWrQy1YSn

      HTTP_TIMEOUT: 10
      PORT: 3000

      EVERY_ISS: 30
      EVERY_OSDR: 300
      EVERY_APOD: 3600
      EVERY_NEO: 3600
      EVERY_DONKI: 3600
      EVERY_SPACEX: 600
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "3000:3000"

  php:
    build:
      context: ./services/php-web
    container_name: php
    restart: always
    depends_on:
      db:
        condition: service_healthy
      rust_iss:
        condition: service_started
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080

      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: "5432"
      DB_DATABASE: monolith
      DB_USERNAME: monouser
      DB_PASSWORD: monopass

      RUST_ISS_URL: http://rust_iss:3000

      # чтобы Laravel не лез в таблицу cache (и не падал)
      CACHE_STORE: file
      SESSION_DRIVER: file
    volumes:
      - ./services/php-web/app:/var/www/html
      - laravel_storage:/var/www/html/storage
      - laravel_cache:/var/www/html/bootstrap/cache

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ./services/php-web/app:/var/www/html:ro
      - laravel_storage:/var/www/html/storage:ro
      - ./services/php-web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

  legacy:
    build:
      context: ./services/pascal-legacy
    container_name: legacy
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      CSV_OUT_DIR: /data/csv
      PGHOST: db
      PGPORT: "5432"
      PGUSER: monouser
      PGPASSWORD: monopass
      PGDATABASE: monolith
      GEN_PERIOD_SEC: "300"
    volumes:
      - ./data/legacy:/data/csv

volumes:
  laravel_storage:
  laravel_cache:
